# serverless.yml

service: simple-gql-service
provider:
    name: aws
    runtime: nodejs8.10
functions:
    graphql:
        # this is formatted as <FILENAME>.<HANDLER>
        handler: graphql.graphqlHandler
        events:
            - http:
                  path: graphql
                  method: post
                  cors: true
            - http:
                  path: graphql
                  method: get
                  cors: true
